import { useEffect } from 'react';

export default function AboutModal({ onClose }) {
  useEffect(() => {
    const handler = (e) => { if (e.key === 'Escape') onClose(); };
    document.addEventListener('keydown', handler);
    return () => document.removeEventListener('keydown', handler);
  }, [onClose]);

  return (
    <div
      className="modal-overlay"
      role="dialog"
      aria-modal="true"
      aria-labelledby="modal-title"
      onClick={(e) => { if (e.target === e.currentTarget) onClose(); }}
    >
      <div className="modal">
        <div className="modal-header">
          <h2 id="modal-title">About The Muddler</h2>
          <button className="modal-close" onClick={onClose} aria-label="Close">&times;</button>
        </div>
        <div className="modal-body">
          <div className="modal-notice">
            This is a limited web version: max 128-EDO, 6 scale rows, 4 KB input.
            For larger or more complex inputs, use the{' '}
            <a href="https://github.com/ascai1/muddler" target="_blank" rel="noopener">
              full Python script
            </a>.
          </div>

          <p>
            A tool for generating <strong>xenharmonic muddles</strong>: pitch collections
            derived by recursively nesting MOS (Moment of Symmetry) scales inside one another
            across arbitrary EDO (Equal Division of the Octave) spaces.
          </p>

          <h3>Concept</h3>
          <p>
            Begin with a larger MOS over a complete <strong>n₀-EDO</strong> space picking
            out <strong>n₁</strong> notes, then find a smaller MOS within this subspace of
            size <strong>n₂</strong>, and repeat to an arbitrarily nested level.
          </p>
          <ol>
            <li>Start with a large MOS (or any pitch collection) over an <strong>n₀-EDO</strong> space, selecting <strong>n₁</strong> notes.</li>
            <li>Treat that MOS as a "retuned" version of <strong>n₁-EDO</strong> space — the new chromatic universe.</li>
            <li>Find a smaller MOS of size <strong>n₂</strong> within this subspace.</li>
            <li>Repeat to arbitrary depth.</li>
          </ol>
          <p>
            Each resulting pitch collection is called a <strong>muddle</strong>. All possible
            muddles are generated by taking every combination of rotations (modes) across the
            input scales, then grouped by interval-cycle equivalence.
          </p>

          <h3>Input Format</h3>
          <p>Each row defines a scale within the EDO space set by the previous row's note count. Three input types are supported:</p>
          <ul>
            <li><strong>Degrees</strong> — list of 1-indexed scale degrees (e.g. <code>1 3 5 6 8 10 12</code> in 12-EDO)</li>
            <li><strong>Intervals</strong> — list of step sizes between consecutive notes (e.g. <code>2 2 1 2 2 1 2</code>)</li>
            <li><strong>Binary</strong> — one toggle per EDO degree, on or off</li>
          </ul>
          <p>Append <code>locked</code> to a scale line to suppress rotation.</p>

          <h3>Output</h3>
          <p>
            Results are grouped by interval cycle, ordered roughly darkest to brightest.
            Each group lists all distinct modes shown as a grid of highlighted degrees.
            Hover the <em>i</em> button on any mode for its full derivation context.
          </p>

          <h3>Further Reading</h3>
          <p>
            <a href="https://en.xen.wiki/w/Muddle" target="_blank" rel="noopener">Muddle — Xen Wiki</a><br />
            <a href="https://en.xen.wiki/w/MOS_scale" target="_blank" rel="noopener">MOS scale — Xen Wiki</a>
          </p>
        </div>
      </div>
    </div>
  );
}
